# - Krishna, A. (2023, November 27). How to Implement Two-Factor Authentication with PyOTP and Google Authenticator in Your Flask App.
#   freeCodeCamp.org. https://www.freecodecamp.org/news/how-to-implement-two-factor-authentication-in-your-flask-app/
#
# Flask-WTF simplifies form creation by providing built-in form classes,
# input fields, and validation support.

from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, EqualTo, Length, InputRequired

from src.accounts.models import User

# Registration form
# Requires a username and password with minimum length requirements,
# along with password confirmation.
class RegisterForm(FlaskForm):
    username = StringField(
        "Username", validators=[DataRequired(), Length(min=6, max=40)]
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        "Repeat password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )

    # Verify that the username is not already registered
    def validate(self, extra_validators):
        initial_validation = super(RegisterForm, self).validate(extra_validators)
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        if self.password.data != self.confirm.data:
            self.password.errors.append("Passwords must match")
            return False
        return True

# Login form
# Requires a username and password.
class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])

# Two-factor authentication form
# Accepts the 6-digit one-time password (OTP) generated by
# the authenticator application.
class TwoFactorForm(FlaskForm):
    otp = StringField(
        "Enter OTP",
        validators=[InputRequired(), Length(min=6, max=6)]
    )
